### ISSUE TITLE
Add command to look up a game's current price

### ISSUE THREAD

**Issue by acdvs** [acdvs/dealbot#22]
Sometimes it's nice to know the current price of a game regardless of whether it's on sale. The output of this would probably look like the `$deals` output.

**Comment by joshg253** [comment]
This would actually help an issue I see right now:
Quake1 is cheapest on GMG, but that is shown as their regular price so doesn't show up in the $deals output at all, let alone at the top where I'd expect it.

**Comment by acdvs** [comment]
Added with commit 07874b61a87412ce3d12b1834922c264fa0e6836.
